version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - Mael-91
  ignore:
  - dependency-name: webpack
    versions:
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: svg-sprite-loader
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.0.5
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.12
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.8
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
